### PR TITLE
ci: add frontend build check to catch stale artifacts

### PR DESCRIPTION
**Pull request by Svtter**
## Summary

Add CI workflow to verify frontend builds successfully when `frontend/**` files change, preventing stale production artifacts from being silently served.

### `.github/workflows/frontend.yml` (new)
- Triggered on push/PR to main/develop when `frontend/**` changes
- Runs `pnpm install --frozen-lockfile` + `pnpm run build` (`tsc -b && vite build`)
- If `tsc` type-checking fails, CI fails — prevents the exact scenario from #78

### `run.sh`
- Add frontend build step (step 2) before starting the Flask app
- `git clone` + `bash run.sh` is now a complete bootstrap — no manual `npm run build` needed

### `frontend/package.json`
- Add `engines.node: ">=22"` and `packageManager: "pnpm@9.15.0"` to pin runtime versions

## Acceptance criteria

- [x] `tsc` compilation errors are caught by CI (`pnpm run build` runs `tsc -b && vite build`)
- [x] Frontend build is part of the automated pipeline (`run.sh` builds before serving)

## Notes

- `static/dist/` is gitignored, so diff-based freshness checks are not applicable. The CI gate (build must succeed) catches the described failure mode.
- Uses `pnpm` in CI (matching `pnpm-lock.yaml`) and `npm` in `run.sh` (zero-install local dev).

Closes #78

### CODE REVIEW

File: run.sh [hunk 1]
```diff
@@ -29,8 +29,22 @@ else
     echo "✓ 依赖已安装"
 fi
 
+
+echo ""
+echo "2. 构建前端..."
+if [ -d "frontend/node_modules" ]; then
```
Comment (Svitter) [inline run.sh:35]: **should-fix** — `npm install` won't use `pnpm-lock.yaml`, so local dev may resolve different dependency versions than CI (which uses `pnpm install --frozen-lockfile`). The PR notes call this out as intentional ("zero-install local dev"), but it means the CI gate doesn't actually guarantee `run.sh` builds identically. Consider either using `pnpm` here (and adding a prerequisite check) or adding a `package-lock.json` for npm consistency.

File: run.sh [hunk 2]
```diff
@@ -29,8 +29,22 @@ else
     echo "✓ 依赖已安装"
 fi
 
+
+echo ""
+echo "2. 构建前端..."
```
Comment (Svitter) [inline run.sh:34]: **should-fix** — new step 2 invokes `npm` but doesn't check whether `node` / `npm` are installed. The existing script guards `python3` (line 14) and `hugo` (line 48) with `command -v` checks. A missing `npm` will produce a cryptic "command not found" rather than a clear error, and the `$?` error path on line 40 would exit with a reasonable message — but only after `npm` itself prints to stderr. Add a `command -v node` / `command -v npm` guard before the build step for parity.

**Review by Svitter — COMMENTED** [review]
P1 — clean, well-scoped CI gate that catches exactly the failure mode from #78. The `frontend.yml` workflow follows existing repo CI conventions (`test.yml`, `docker-image.yml`) and the `run.sh` integration makes `git clone` + `bash run.sh` a complete bootstrap.

Two should-fix items on `run.sh`:

1. **npm/pnpm mismatch** (line 35–38): `run.sh` uses `npm install` but the lockfile is `pnpm-lock.yaml`, so local dependency resolution can diverge from CI. Consider using `pnpm` here with a guard, or pinning with a `package-lock.json`.
2. **Missing `node`/`npm` prerequisite check** (line 34): the script checks for `python3` and `hugo` but not the runtime the new step requires.

Neither is blocking. Thanks for the PR.
